baseURL = "https://www.tquelch.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Tim Quelch"

theme = "LoveIt"

googleAnalytics = "G-2K1E1DZ3HF"

[author]
name = "Tim Quelch"
link = "/"
email = "tim@tquelch.com"

[params]
version = "0.2.X"
description = "Tim Quelch's blog and portfolio"
keywords = ["blog", "portfolio", "phd", "personal"]

[params.home]
[params.home.profile]
title = "Tim Quelch"
subtitle = "PhD Student at University of Melbourne"
avatarURL = "/images/me.jpg"
typeit = false
social = true

[params.footer]
enable = true
hugo = false
since = "2020"

[params.social]
GitHub = "TimQuelch"
LinkedIn = "TimQuelch"
Twitter = "TimQuelch"
email = "tim@tquelch.com"

[params.page]
ruby = false
fraction = false
fontawesome = false
linkToMarkdown = false
rssFullText = true

[params.page.toc]
enable = true
keepStatic = false
auto = true

[params.page.math]
enable = true
copytex = false
mhchem = false

[params.page.code]
copy = false

[params.page.comment]
enable = false

[params.page.share]
enable = false

[params.search]
enable = false

[params.cookieconsent]
enable = false

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params.analytics]
enable = true
[params.analytics.google]
id = "G-2K1E1DZ3HF"

[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true

# Defining menu items that aren't defined in content.org
[[menu.main]]
name = "Posts"
weight = 10
url  = "posts/"

# Define deployment
[deployment]
[[deployment.targets]]
name = "awsdeploy"
URL = "s3://tquelch.com?region=ap-southeast-2"
cloudFrontDistributionID = "E3VDV2G1945VZE"

# Cache static assets for a year. Compress things that are compressible
# This is just taken from https://gohugo.io/hosting-and-deployment/
[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
