baseURL = "https://www.tquelch.com/"
languageCode = "en"
defaultContentLanguage = "en"

googleAnalytics = "G-2K1E1DZ3HF"

[author]
name = "Tim Quelch"
link = "/"
email = "tim@tquelch.com"

[params]
title = "Tim Quelch"
description = "Tim Quelch's blog and portfolio"
images = ['/images/me-small.jpg']
keywords = ["blog", "portfolio", "phd", "personal"]
locale = "en_AU"

[params.home]
title = "Tim Quelch"
subtitle = "PhD Student at University of Melbourne"
photoURL = "/images/me-small.jpg"

[params.footer]
since = "2020"
license = "<a rel=\"license\" href=\"/about/#license\">CC BY 4.0</a>"

[params.categories]
linksshown = 5

# Defining menu items that aren't defined in content.org
[[menu.main]]
name = "Posts"
weight = 10
url  = "posts/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokailight"
tabWidth = 4

# Define deployment
[deployment]
[[deployment.targets]]
name = "awsdeploy"
URL = "s3://tquelch.com?region=ap-southeast-2"
cloudFrontDistributionID = "E3VDV2G1945VZE"

# Cache static assets for a year. Compress things that are compressible
# This is just taken from https://gohugo.io/hosting-and-deployment/
[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
