#+hugo_base_dir: .
#+csl_style: build/ieee.csl
#+options: author:nil

* Contact
:PROPERTIES:
:export_hugo_section: /
:export_hugo_menu: :menu main :weight 3
:export_file_name: contact
:END:

#+begin_export html
<style> .contact_table th, .contact_table td {border: 0!important; padding: 0px 15px;} </style>
#+end_export
#+attr_html: :class contact_table
|                  |                                   |
| *Email*          | [[mailto:tim@tquelch.com][tim@tquelch.com]]                   |
| *Uni email*      | [[mailto:tim.quelch@student.unimelb.edu.au][tim.quelch@student.unimelb.edu.au]] |
| *GitHub*         | [[https://github.com/TimQuelch][github.com/TimQuelch]]              |
| *LinkedIn*       | [[https://linkedin.com/in/TimQuelch][linkedin.com/in/TimQuelch]]         |
| *Twitter*        | [[https://twitter.com/TimQuelch][twitter.com/TimQuelch]]             |
| *GPG Public Key* | [[file:static/key.asc][key.asc]]                           |

* TODO About
:PROPERTIES:
:export_hugo_section: /
:export_hugo_menu: :menu main :weight 2
:export_file_name: about
:END:

hi
* Projects
:PROPERTIES:
:export_hugo_section: /
:export_hugo_menu: :menu main :weight 4
:export_file_name: projects
:END:

** My notes
:PROPERTIES:
:ID:       99331808-d401-476d-a41a-6f168e7bbd2f
:END:

Just before starting my PhD I came across the [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten]] method as well as the book /How to take Smart Notes/ by Sonke Ahrens autocite:ahrensHowTakeSmart2017. Zettelkasten is a method of non-hierarchical note taking where notes contain information about a single topic and are linked together to make manual connections. I've implemented my notes repository in [[https://www.gnu.org/software/emacs/][Emacs]] [[https://orgmode.org/][org mode]] and the [[https://github.com/org-roam/org-roam][org-roam]] package.

While I've not made my notes public, I have done some data analysis and tracking of them the code which I have made public.
- [[https://github.com/TimQuelch/notes-snapshot][notes-snapshot]]: contains the scripts and ~systemd~ unit files that I use to regularly take snapshots of my notes
- [[https://github.com/TimQuelch/notes-timeline][notes-timeline]]: contains my data analysis written in ~Julia~

** OrgMode.jl

Many of my [[id:99331808-d401-476d-a41a-6f168e7bbd2f][notes]] and task management is written in [[https://orgmode.org][org mode]]. As part of my data analysis of my notes, I need to parse the ~.org~ files to differentiate the content within the files. I created [[https://github.com/TimQuelch/OrgMode.jl][OrgMode.jl]] in Julia so I had a nice native interface for my data analysis.
* Posts
:PROPERTIES:
:export_hugo_section: posts
:END:
** TODO This is a test post
:PROPERTIES:
:export_file_name: test-post
:END:

Here I am writing a test post
** Workflow :@workflow:
*** TODO My email workflow :notmuch:emacs:email:
:PROPERTIES:
:export_file_name: my-email
:END:

Talking about my email workflow

*** TODO My notetaking workflow :emacs:notes:
:PROPERTIES:
:export_file_name: my-notes
:END:

Talking about my notes workflow
